### ISSUE TITLE
Need a 1024 x 1024 logo for Facebook app

### ISSUE THREAD

**Issue by mcorsen** [cyril-thomas/wod-dojo#16]
Before users can post a WOD to their Facebook page, we need to pass a Facebook login review. One of the requirements of the review is to set a 1024 by 1024 logo for the app.

**Comment by mcorsen** [comment]
Melissa, could you put together a logo?

**Comment by TomPetr** [comment]
![woddojo-7 -smalljpg](https://cloud.githubusercontent.com/assets/6522568/9421412/0eecc6f2-4830-11e5-98cf-5f3556370f58.jpg)

**Comment by TomPetr** [comment]
![logo-simple_1](https://cloud.githubusercontent.com/assets/6522568/9421775/41256528-4837-11e5-9ea8-f29c5682321f.jpg)
![logo-simple_text](https://cloud.githubusercontent.com/assets/6522568/9421774/41252d24-4837-11e5-92c6-728bfb79ae2a.jpg)

**Comment by melissa-gill** [comment]
I will get you one as soon as we decide on the colors for the one I attached to slack.
